# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7f32291c0f68b58d1bdcfa36a09fdf22b86106d9424387ccec907f96f36f69600cac1a10ed901c45bb81162bfcae50509c3895fe236024c0fa84d0645b2f2051

test:
  secret_key_base: 0c28187e94de6640866b5b59f822a086d7c55d5236ae35eb1f976262702fbf1fe3d490fb4adc138ef405d24d2e9c6a9f8da44df17aa65caf263465331cf21a5e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
